dev_mode: false
host: 127.0.0.1
port: 8888
max_workers: 10
devices:
- id: wled-enc1-cir1
  type: e131
  config:
    name: wled-enc1-cir1
    ip_address: 192.168.10.9
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
- id: wled-enc1-cir2
  type: e131
  config:
    name: wled-enc1-cir2
    ip_address: 192.168.10.10
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
- id: wled-enc2-cir1
  type: e131
  config:
    name: wled-enc2-cir1
    ip_address: 192.168.10.11
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
- id: wled-enc2-cir2
  type: e131
  config:
    name: wled-enc2-cir2
    ip_address: 192.168.10.6
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
- id: wled-enc3-cir1
  type: e131
  config:
    name: wled-enc3-cir1
    ip_address: 192.168.10.12
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
- id: wled-enc3-cir2
  type: e131
  config:
    name: wled-enc3-cir2
    ip_address: 192.168.10.13
    pixel_count: 600
    universe: 1
    universe_end: 4
    universe_size: 510
    center_offset: 0
    refresh_rate: 60
    channel_count: 1800
    channel_offset: 0
    force_refresh: false
    max_brightness: 1.0
    preview_only: false
segment_groups:
- name: enc1-cir1
  segments:
  - name: enc1-cir1
    device_id: wled-enc1-cir1
    pixel_start: 0
    pixel_end: 600
- name: enc1-cir2
  segments:
  - name: enc1-cir2
    device_id: wled-enc1-cir2
    pixel_start: 0
    pixel_end: 600

- name: enc2-cir1
  segments:
  - name: enc2-cir1
    device_id: wled-enc2-cir1
    pixel_start: 0
    pixel_end: 600
- name: enc2-cir2
  segments:
  - name: enc2-cir2
    device_id: wled-enc2-cir2
    pixel_start: 0
    pixel_end: 600

- name: enc3-cir1
  segments:
  - name: enc3-cir1
    device_id: wled-enc3-cir1
    pixel_start: 0
    pixel_end: 600
- name: enc3-cir2
  segments:
  - name: enc3-cir2
    device_id: wled-enc3-cir2
    pixel_start: 0
    pixel_end: 600
